version: '3'
services:
  webapp:
    environment:
      - "ConnectionStrings:PostgreSql=User ID=admin;Password=Password12*;Server=db;Port=5432;Database=blogDb;Integrated Security=true;Pooling=true"
      - "ConnectionStrings:PostgreSqlTest=User ID=admin;Password=Password12*;Server=db;Port=5432;Database=blogDb;Integrated Security=true;Pooling=true"

    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: db
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Password12*
      POSTGRES_DB: blogDb
